# https://github.com/renovate-reproductions/12260/blob/main/.github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4 # Comment that Renovate bot will remove later on

      - name: Run a one-line script
        run: echo Hello, world!

